#서버 포트번호 지정
server:
  port: 8009
  
#인코딩(UTF-8)
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true      

  tomcat:
    uri-encoding: UTF-8


#뷰 리졸버
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp  

  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 651031500816-k9i9geji4ko8sffg14odag9dhrhvq2di.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: dV1gYx6S4XYEw9OMFOMV
            client-secret: aEFt1u18yo
            scope:
            - email
            - name
            - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8009/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 전달할 때 response라는 KEY값으로 데이터를 전달.

#DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/instagram?useUnicode=true
    username: root
    password: toor 
mybatis:
  mapper-locations:
  - /mappers/*.xml
      
file:
  path: C:\fileupload\
  
test:
  filename: test_file.txt




